- name: Configure Master
  hosts: master
  become: true
  become_method: sudo
  roles:
    - common
    - docker
    - kubectl

# - name: Configure Worker
#   hosts: worker
#   become: true
#   become_method: sudo
#   roles: 
#     - docker
#     - common
#     - kubectl


